### PR TITLE
Function calls in C++

### PR DESCRIPTION
**Pull request by ShubhamJagtap2000**
Added code files and README to show how we can call a function in CPP

### CODE REVIEW

**Review by programmer-offbeat — APPROVED** [review]
yoo ! That's some cool guide. Awesome !!

**Comment by programmer-offbeat** [comment]
Thanks so much for the contribution. Make sure to add a star :)

**Comment by ShubhamJagtap2000** [comment]
> Thanks so much for the contribution. Make sure to add a star :)

Yes. More contributions to come.

**Comment by programmer-offbeat** [comment]
I'll be waiting :)

**Pull request merged**
