### PR TITLE
Pointers in C++

### PR DESCRIPTION
**Pull request by ShubhamJagtap2000**
Added well-documented code for working with pointers in C++ including various data types.

### CODE REVIEW

**Review by programmer-offbeat — CHANGES_REQUESTED** [review]
the variables look alike : https://www.good-codes.com/c-declare-a-pointer-cpp/

**Comment by ShubhamJagtap2000** [comment]
> the variables look alike : https://www.good-codes.com/c-declare-a-pointer-cpp/

This is surprising. I coded it during youtube tutorial learning years ago.

**Comment by ShubhamJagtap2000** [comment]
> the variables look alike : https://www.good-codes.com/c-declare-a-pointer-cpp/

No. I did not find any major similarities. Looks good in my view. Can you suggest exactly what you are encountering?

**Comment by programmer-offbeat** [comment]
Ah, nevermind. All cool:)

**Pull request merged**
